"""initial schema

Revision ID: 4e9d21bb514c
Revises: 
Create Date: 2026-03-03 19:47:54.791557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9d21bb514c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('home_rink_address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('league_affiliation', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rinks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zip_codes',
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('association_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('manager_name', sa.String(length=200), nullable=False),
    sa.Column('manager_email', sa.String(length=200), nullable=False),
    sa.Column('manager_phone', sa.String(length=30), nullable=False),
    sa.Column('rink_city', sa.String(length=100), nullable=False),
    sa.Column('rink_state', sa.String(length=2), nullable=False),
    sa.Column('rink_zip', sa.String(length=10), nullable=False),
    sa.Column('myhockey_ranking', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ice_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rink_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booked_by_team_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['rink_id'], ['rinks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ice_slots', schema=None) as batch_op:
        batch_op.create_index('ix_ice_slots_rink_date_status', ['rink_id', 'date', 'status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('notif_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'notif_type', 'week_start', name='uq_notifications_team_type_week')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_team_created', ['team_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_team_read', ['team_id', 'read_at'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ix_players_team_last_first', ['team_id', 'last_name', 'first_name'], unique=False)

    op.create_table('schedule_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opponent_name', sa.String(length=200), nullable=True),
    sa.Column('opponent_team_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weekly_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_team_date_status', ['team_id', 'date', 'status'], unique=False)

    op.create_table('game_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('home_schedule_entry_id', sa.String(length=36), nullable=False),
    sa.Column('away_schedule_entry_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=False),
    sa.Column('proposed_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed_by_team_id', sa.String(length=36), nullable=False),
    sa.Column('ice_slot_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_schedule_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_schedule_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['ice_slot_id'], ['ice_slots.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('ice_slot_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ice_slot_id'], ['ice_slots.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_bookings', schema=None) as batch_op:
        batch_op.create_index('ix_practice_bookings_team_id_status', ['team_id', 'status'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('home_schedule_entry_id', sa.String(length=36), nullable=True),
    sa.Column('away_schedule_entry_id', sa.String(length=36), nullable=True),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('ice_slot_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_weekly_confirmed', sa.Boolean(), nullable=False),
    sa.Column('away_weekly_confirmed', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_schedule_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_schedule_entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['ice_slot_id'], ['ice_slots.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['game_proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', name='uq_games_proposal_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('ix_games_away_team_date', ['away_team_id', 'date'], unique=False)
        batch_op.create_index('ix_games_date', ['date'], unique=False)
        batch_op.create_index('ix_games_home_team_date', ['home_team_id', 'date'], unique=False)

    op.create_table('proposal_rink_preferences',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('rink_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['game_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rink_id'], ['rinks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    with op.batch_alter_table('proposal_rink_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_proposal_rink_preferences_rink_id', ['rink_id'], unique=False)

    op.create_table('game_goalie_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('shootout_shots', sa.Integer(), nullable=False),
    sa.Column('shootout_saves', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_game_goalie_stats_game_player')
    )
    with op.batch_alter_table('game_goalie_stats', schema=None) as batch_op:
        batch_op.create_index('ix_game_goalie_stats_game_team', ['game_id', 'team_id'], unique=False)

    op.create_table('game_penalties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('penalty_type', sa.String(length=100), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_penalties', schema=None) as batch_op:
        batch_op.create_index('ix_game_penalties_game_team', ['game_id', 'team_id'], unique=False)

    op.create_table('game_player_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots_on_goal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_game_player_stats_game_player')
    )
    with op.batch_alter_table('game_player_stats', schema=None) as batch_op:
        batch_op.create_index('ix_game_player_stats_game_team', ['game_id', 'team_id'], unique=False)

    op.create_table('game_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'role', name='uq_game_signatures_game_role')
    )
    with op.batch_alter_table('game_signatures', schema=None) as batch_op:
        batch_op.create_index('ix_game_signatures_game', ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_signatures', schema=None) as batch_op:
        batch_op.drop_index('ix_game_signatures_game')

    op.drop_table('game_signatures')
    with op.batch_alter_table('game_player_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_game_player_stats_game_team')

    op.drop_table('game_player_stats')
    with op.batch_alter_table('game_penalties', schema=None) as batch_op:
        batch_op.drop_index('ix_game_penalties_game_team')

    op.drop_table('game_penalties')
    with op.batch_alter_table('game_goalie_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_game_goalie_stats_game_team')

    op.drop_table('game_goalie_stats')
    with op.batch_alter_table('proposal_rink_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_rink_preferences_rink_id')

    op.drop_table('proposal_rink_preferences')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_home_team_date')
        batch_op.drop_index('ix_games_date')
        batch_op.drop_index('ix_games_away_team_date')

    op.drop_table('games')
    with op.batch_alter_table('practice_bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_bookings_team_id_status')

    op.drop_table('practice_bookings')
    op.drop_table('game_proposals')
    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_team_date_status')

    op.drop_table('schedule_entries')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('ix_players_team_last_first')

    op.drop_table('players')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_team_read')
        batch_op.drop_index('ix_notifications_team_created')

    op.drop_table('notifications')
    with op.batch_alter_table('ice_slots', schema=None) as batch_op:
        batch_op.drop_index('ix_ice_slots_rink_date_status')

    op.drop_table('ice_slots')
    op.drop_table('teams')
    op.drop_table('zip_codes')
    op.drop_table('rinks')
    op.drop_table('associations')
    # ### end Alembic commands ###
