"""add website to rinks

Revision ID: cd71b93b406b
Revises: 4e9d21bb514c
Create Date: 2026-03-03 22:19:22.237878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd71b93b406b'
down_revision: Union[str, Sequence[str], None] = '4e9d21bb514c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rinks', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
